CC=gcc
CXX=g++
CXXFLAGS=-std=c++11 -Wall -pedantic

intcell_driver.x: intcell.o intcell_driver.o
	$(CXX) $(CXXFLAGS) -o intcell_driver.x intcell.o intcell_driver.o

intcell.o: intcell.h intcell.cpp
	$(CXX) $(CXXFLAGS) -c -o intcell.o intcell.cpp

memorycell_driver.x: memorycell.h memorycell.hpp memorycell_driver.cpp
	$(CXX) $(CXXFLAGS) -o memorycell_driver.x memorycell_driver.cpp


.SUFFIXES: .x

.PHONY : clean

clean:
	rm -f *.o *.x core.*

%.x : %.c
	$(CC) -o $@ $<
%.x : %.cpp
	$(CXX) $(CXXFLAGS) -o $@ $<
%.o : %.cpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<
